### PR TITLE
Log how long SDR processing took

### PR DESCRIPTION
**Pull request by gerritholl**
This PR adds logging for how long the CSPP SDR processing took, both in terms since the processing started and in terms since the granule started.  Such logging will help us to assess performance on our systems.

 - [ ] Closes #xxxx 
 - [x] Tests added 
 - [x] Tests passed: Passes ``pytest cspp_runner`` 
 - [x] Passes ``flake8`` 
 - [ ] Fully documented

### CODE REVIEW

**Comment by gerritholl** [comment]
I just realised this already exists, at least partly:

https://github.com/pytroll/pytroll-cspp-runner/blob/0201dc98e70f56f1ae933868afbca743bf0e2dd5/cspp_runner/runner.py#L276-L277

**Comment by adybbroe** [comment]
@gerritholl I am about to add an ATMS runner, so would perhaps be good to start from a master where we have the latest work merged. Would this be ready for review now?

**Comment by TAlonglong** [comment]
This is still a draft as far as I can see

**Review by adybbroe — APPROVED** [review]
LGTM

**Review by TAlonglong — APPROVED** [review]
Looks good to me

**Pull request merged**
